### ISSUE TITLE
Download individual templates as wav

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon-legacy#1386]
![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/3c4f7638-6734-48d5-8f67-65f371d64f36)

[Video](https://github.com/rfcx/arbimon-legacy/assets/47339266/0cd5270f-3399-4cb3-b257-edadb7f69716)
[Figma](https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=9495%3A108386&mode=design&t=Vtidibbb0LCrMxCK-1)

## Tasks
- [x] Add download button to the project templates
- [x] Download template in the selected area as wav format
- [x] Permission to download: any other roles except viewer/guest

## Addtional update tasks
- [x] Update delete icon with danger colours
- [x] Updated the create job buttons style to match the brand
- [x] Updated taxa filter wording and style
- [x] Updated search bar style
- [x] Updated publish template to public library toggle style ("OFF" is more readable) - _[TBD]_

## Expected results
- [x] User can download project template in wav format
- [x] User can download public template added to the project
- [ ] User should not be able to download template added to the project from public library

----
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Proposed by @carlybatist  [on eng-support](https://rfcx.slack.com/archives/C03FD1WD02J/p1701121487443219)
> Can we add a function that allows Arbimon users to download templates/bounding box labels? Right now there is only the ability to download the full 1-minute recordings.
