### ISSUE TITLE
Legacy - add ability for user to hide site

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon-legacy#1490]
![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/07c881ea-203d-41c8-89e2-5dff290048ac)
[Prototype video](https://github.com/rfcx/arbimon/assets/47339266/371644c3-6ed1-45cf-a869-46fc8198dcbd)
[Figma](https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=9486%3A24710&mode=design&t=Vtidibbb0LCrMxCK-1)

## Tasks
- [x] Update style and color of edit site pop up
- [x] Add checkbox “Exclude site from analyses and Insights” on edit site pop up 
- [x] Add info icon for “Exclude site from analyses and Insights” using description "[TD - waiting from Carly]"
- [x] Disable location fields (lat, long, el) when the checkbox is checked
- [x] Sites with “Exclude site from analyses and Insights” checkbox checked or has empty long, lat, will have “-” for long, lat, alt, el and timezone column
- [x] Hide site 0,0 or other virtual site from the map 
- [x] Add icon in site list to inform user which site is hidden

## Expected results
- [x] User can hide site by checking the checkbox inside edit site
- [x] When user checks the checkbox, the lat, lon, alt should be disable
- [x] When user unchecks the checkbox, the lat, lon, alt should be enable
- [x] Hidden site will show - for the coordinates? [TBD]
- [x] The hidden site will have the icon indicate the status
- [x] The hidden site will not show on the Insights map
- [x] The hidden site data (recordings and validations) will not show on Insights and Global report
- [x] The hidden site will be excluded from number of sites created (overview)
- [x] The number of recordings in the hidden site will not be included to the total of recordings in the project

## Error states
- [ ] Save change unsuccess
