### ISSUE TITLE
Add selecting range of time on Recordings filters

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1495]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1705520808163419
From: Carly

Design 
![Image](https://github.com/rfcx/arbimon/assets/87486094/136de41a-5571-463f-a207-04940618034f)

![Image](https://github.com/rfcx/arbimon/assets/87486094/2339296b-3c0a-4a97-a68f-4481ea533530)

## Tasks
1. Filter pop up
- [x] rearrange fields (group)
- [x] relocation "Reset" and "Apply filter" buttons
- [x] change "Apply filter" button color

2. Hour dropdown
- [x] add select all on top of hour dropdown
- [x] highlight selected hours
- [x] allow to select multiple hours
- [x] keep dropdown open until user clicks out of the dropdown to close
- [x] same color and style as Filter pop up
- [x] when select all is selected, deselect other hours (should not be able to select "select all' with other hours)
- [x] deleted selected hours should be deleted from the top of dropdown and not highlighted in the list
- [x] when select all and then select individual hours, select all should be deselected
- [x] deselect "select all" then select individual hours should replace selected hours on top of the dropdown (replace select all hours (24hours))
- [x] when select "select all", show 3 rows of hours on top of dropdown 

https://github.com/rfcx/arbimon/assets/87486094/338175c3-f482-43af-8dcc-effba9a4dffc

## Expected results
- [x] User can select multiple hours 
- [x] Hour dropdown stays open until clicking outside the dropdown
- [x] When selected some hours and select "select all", all hours should be selected
- [x] When user deletes any hour, deleted hour should be disappear from the selected list (top of dropdown and not highlighted)
- [x] When user selects "select all", it should show 3 rows of hours on top of dropdown and able to scroll up/down for more hours

>I know this has been brought up before, and I thought it was going to be a fix that was implemented on the new site updates but it's not showing on dev.
It would be so helpful if when filtering recordings, you could select a time range rather than having to select every hour individually like you do right now. If we want to make a nocturnal playlist for example, we have to select 19:00, 20:00, 21:00, etc. etc. and it would be great if we could just say 19:00-06:00 as a range.
