### ISSUE TITLE
Sync - Add timestamp fields to the table for Bio Report

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon-legacy#949]
#### Background: 

As Biodiversity Report has a sync job to sync data from Arbimon incrementally, it's important that we know the last updated at of each row so we can pull the newly updated data only.

List of tables that Bio reports need data from: 
- projects
- sites
- species
- recordings
- recording_validations

#### Tasks:
- [ ] Add `created_at`, `updated_at`, `deleted_at` to projects table
- [ ] Add `created_at`, `updated_at`, `deleted_at` to species table
- [ ] Add  `deleted_at` to recordings table
- [ ] Add `created_at`, `updated_at`, `deleted_at` to recordings_validations table
